import { StyleSheet } from 'react-native';
import { themes } from '../../global/themes';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    paddingTop: 40,
  },
  header: {
    fontSize: 22,
    fontWeight: 'bold',
    color: themes.colors.purpleDark,
    textAlign: 'center',
    marginBottom: 10,
  },
  listContent: {
    paddingBottom: 16,
  },
  card: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    width: '95%',
    maxWidth: 350,
    alignSelf: 'center',
    
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0, 
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,

    elevation: 8,
  },
  topInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  checkbox: {
    width: 28,
    height: 28,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: themes.colors.purpleDark,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  checkboxChecked: {
    backgroundColor: themes.colors.purpleDark,
  },
  checkboxTick: {
    width: 10,
    height: 6,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    borderColor: '#fff',
    transform: [{ rotate: '-45deg' }],
  },
  leftColumn: {
    alignItems: 'center',
    marginRight: 12,
  },
  image: {
    width: 100,
    height: 130,
    marginBottom: 10,
    marginTop: 10,
  },
  qtdContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themes.colors.purpleDark,
    borderRadius: 15,
    overflow: 'hidden',
    height: 35,
  },
  qtdButton: {
    width: 35,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  qtdText: {
    color: 'white',
    fontSize: 20,
    marginBottom: 5,
  },
  qtdTextMiddle: {
    color: themes.colors.purpleDark,
    fontWeight: 'bold',
    fontSize: 16,
  },
  qtdMiddle: {
    backgroundColor: 'white',
    width: 40,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: themes.colors.purpleDark,
  },
  infoContainer: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  title: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#333',
  },
  author: {
    fontSize: 13,
    color: '#666',
    marginBottom: 2,
  },
  type: {
    fontSize: 13,
    color: '#333',
    fontWeight: 'bold',
    marginBottom: 2,
  },
  inStock: {
    fontSize: 13,
    color: 'green',
    marginBottom: 4,
  },
  price: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#000',
    marginTop: 4,
  },
  totalBox: {
    position: 'absolute',
    bottom: 0, 
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderColor: '#ccc',
    width: '100%', 
    boxShadow: themes.colors.shadow,
  },
  
  totalInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  totalLabel: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  totalValue: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333',
  },
  semFrete: {
    color: 'orange',
    marginBottom: 8,
    fontSize: 12,
  },
  checkoutButton: {
    backgroundColor: themes.colors.primary,
    padding: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 8,
  },
  checkoutText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
  },
  loading: {
    position: 'absolute',
    top: '30%',
    left: '50%',
    transform: [{ translateX: -20 }, { translateY: 75 }],
    zIndex: 10,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyText: {
    fontSize: 18,
    color: themes.colors.purpleDark,
    textAlign: 'center',
    marginTop: -60,
  },
  separator: {
    height: 2,
    backgroundColor: themes.colors.purpleDark,
    width: '100%',
    marginVertical: 15,
  },
  trashButtonItem: {
    position: 'absolute',
    top: 0,
    right: 0,
    padding: 6,
    zIndex: 10,
  },
  checkboxContainerItem: {
    marginLeft: 10,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  separatorPurple: {
    height: 2,
    backgroundColor: themes.colors.purpleDark,
    width: '90%',
    marginVertical: 12,
    borderRadius: 4,
    alignSelf: 'center',
  },
});

export default styles;
