"""Adicionando relacionamento em ItemPedido

Revision ID: 16f24b15dcf9
Revises: f7495bec96b5
Create Date: 2025-04-18 22:40:54.542976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f24b15dcf9'
down_revision = 'f7495bec96b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemPedido', schema=None) as batch_op:
        batch_op.alter_column('id_pedido',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('id_livro',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemPedido', schema=None) as batch_op:
        batch_op.alter_column('id_livro',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id_pedido',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
