"""Criando Tabela de GeneroLivro

Revision ID: 796c5bd681d0
Revises: b77f13e59504
Create Date: 2025-04-15 23:26:04.210876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796c5bd681d0'
down_revision = 'b77f13e59504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GeneroLivro',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GeneroLivro')
    # ### end Alembic commands ###
