"""Criando Tabela de Endereço

Revision ID: 7d2813afc6d4
Revises: 8931a14a9043
Create Date: 2025-04-15 23:19:49.992756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2813afc6d4'
down_revision = '8931a14a9043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Endereco',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('bairro', sa.String(length=40), nullable=False),
    sa.Column('rua', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['Estado.id'], name='fk_endereco_estado', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], name='fk_endereco_usuario', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Endereco')
    # ### end Alembic commands ###
