"""Adicionando relacionamento em ItemCarrinho

Revision ID: f7495bec96b5
Revises: 83004948b8a2
Create Date: 2025-04-18 20:57:28.638148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7495bec96b5'
down_revision = '83004948b8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemCarrinho', schema=None) as batch_op:
        batch_op.alter_column('id_carrinho',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('id_livro',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemCarrinho', schema=None) as batch_op:
        batch_op.alter_column('id_livro',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id_carrinho',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
