"""Criando Tabela de Autor

Revision ID: b77f13e59504
Revises: 7d2813afc6d4
Create Date: 2025-04-15 23:21:22.674647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77f13e59504'
down_revision = '7d2813afc6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Autor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('biografia', sa.Text(), nullable=False),
    sa.Column('foto', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Autor')
    # ### end Alembic commands ###
