"""Criando Tabela de Livro

Revision ID: fcff2451b72b
Revises: 796c5bd681d0
Create Date: 2025-04-15 23:27:50.778169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcff2451b72b'
down_revision = '796c5bd681d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Livro',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.Column('foto', sa.Text(), nullable=False),
    sa.Column('sinopse', sa.String(length=350), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('formato', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_autor'], ['Autor.id'], name='fk_livro_autor', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_genero'], ['GeneroLivro.id'], name='fk_livro_genero', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Livro')
    # ### end Alembic commands ###
