"""Criando Tabela de Pagamento

Revision ID: 1c5d74e9636e
Revises: 3b67078c9d80
Create Date: 2025-04-15 23:33:22.682232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5d74e9636e'
down_revision = '3b67078c9d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pagamento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pagamento')
    # ### end Alembic commands ###
