"""Criando Tabela de Estado

Revision ID: 8931a14a9043
Revises: 04b8a90529a1
Create Date: 2025-04-15 23:18:29.339097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8931a14a9043'
down_revision = '04b8a90529a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Estado',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Estado')
    # ### end Alembic commands ###
