"""Criando Tabela de ItemPedido

Revision ID: dae92257c279
Revises: a84bf6032e42
Create Date: 2025-04-15 23:36:22.086837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae92257c279'
down_revision = 'a84bf6032e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItemPedido',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_livro', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_livro'], ['Livro.id'], name='fk_itempedido_livro', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pedido'], ['Pedido.id'], name='fk_itempedido_pedido', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ItemPedido')
    # ### end Alembic commands ###
