import { StyleSheet } from "react-native";
import { themes } from '../../global/themes';

const styles = StyleSheet.create({
    container: {
        alignItems: 'center',
        backgroundColor: themes.colors.backgroundLumyk,
        padding: 20,
        flexGrow: 1,
    },
    image: {
        width: 150,
        height: 220,
        resizeMode: 'contain',
        marginVertical: 20,
        borderRadius: 10,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginTop: 10,
        color: '#000',
    },
    author: {
        fontSize: 16,
        color: '#555',
        marginTop: 2,
    },
    stock: {
        fontSize: 14,
        color: 'green',
        marginTop: 5,
        marginBottom: 20,
    },
    formatContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 20,
        gap: 10,
    },
    formatButton: {
        backgroundColor: '#fff',
        borderRadius: 10,
        paddingVertical: 15,
        paddingHorizontal: 12,
        width: '47%',
        alignItems: 'center',
        marginVertical: 5,
        elevation: 4,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
    },
    selectedButton: {
        borderColor: '#fff',
        borderWidth: 1,
    },
    formatTitle: {
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 6,
        color: '#333',
    },
    separator: {
        width: '100%',
        height: 1,
        backgroundColor: '#ccc',
        marginBottom: 8,
    },
    formatContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    circle: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#999',
        alignItems: 'center',
        justifyContent: 'center',
    },
    filledCircle: {
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: themes.colors.primary,
    },
    priceText: {
        fontSize: 13,
        color: '#555',
    },
    addToCartButton: {
        backgroundColor: themes.colors.primary,
        paddingVertical: 14,
        paddingHorizontal: 60,
        borderRadius: 30,
        marginBottom: 30,
        elevation: 3,
    },
    addToCartText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    bottomBox: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 20,
        alignItems: 'flex-start',
        width: '100%',
        marginTop: 20,
        elevation: 4,
    },
    description: {
        fontSize: 14,
        textAlign: 'justify',
        marginBottom: 20,
        color: '#333',
    },
    bottomImage: {
        width: 160,
        height: 200,
        resizeMode: 'contain',
        marginBottom: 15,
        borderRadius: 10,
        alignSelf: 'center',
    },
    bottomText: {
        fontSize: 14,
        color: '#333',
        marginBottom: 15,
        alignSelf: 'center',
    },
    viewBooksButton: {
        backgroundColor: themes.colors.primary,
        paddingVertical: 10,
        paddingHorizontal: 25,
        borderRadius: 20,
        alignSelf: 'flex-end',
        marginTop: 10,
    },
    viewBooksButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '600',
    },
    dropdownContent: {
        backgroundColor: '#fff',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 6,
        marginTop: 8,
        elevation: 5,
        position: 'absolute',
        zIndex: 10,
        width: '47%',
        right: 0, 
    },
    dropdownItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 10,
        justifyContent: 'space-between',
    },
    dropdownItemText: {
        fontSize: 12,
        color: '#333',
    },
    dropdownCircle: {
        width: 16,
        height: 16,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#999',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dropdownFilledCircle: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: themes.colors.primary,
    },
});

export default styles;
