"""Criando Tabela de ItemCarrinho

Revision ID: 3b67078c9d80
Revises: 5b39c38a1918
Create Date: 2025-04-15 23:31:15.250901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b67078c9d80'
down_revision = '5b39c38a1918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItemCarrinho',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_carrinho', sa.Integer(), nullable=False),
    sa.Column('id_livro', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrinho'], ['Carrinho.id'], name='fk_itemcarrinho_carrinho', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_livro'], ['Livro.id'], name='fk_itemcarrinho_livro', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ItemCarrinho')
    # ### end Alembic commands ###
