"""Adicionando chave estrangeira de Estado em Livro

Revision ID: 435500c4fae8
Revises: 16f24b15dcf9
Create Date: 2025-04-20 20:15:00.311846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435500c4fae8'
down_revision = '16f24b15dcf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_Livro')
    with op.batch_alter_table('Livro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_estado', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('id_usuario', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('id_endereco', sa.String(length=36), nullable=True))
        batch_op.alter_column('id_genero',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('id_autor',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_livro_usuario', 'Usuario', ['id_usuario'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_livro_endereco', 'Endereco', ['id_endereco'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_livro_estado', 'Estado', ['id_estado'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Livro', schema=None) as batch_op:
        batch_op.drop_constraint('fk_livro_estado', type_='foreignkey')
        batch_op.drop_constraint('fk_livro_endereco', type_='foreignkey')
        batch_op.drop_constraint('fk_livro_usuario', type_='foreignkey')
        batch_op.alter_column('id_autor',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id_genero',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('id_endereco')
        batch_op.drop_column('id_usuario')
        batch_op.drop_column('id_estado')

    op.create_table('_alembic_tmp_Livro',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('id_genero', sa.VARCHAR(length=36), nullable=False),
    sa.Column('id_autor', sa.VARCHAR(length=36), nullable=False),
    sa.Column('foto', sa.TEXT(), nullable=False),
    sa.Column('sinopse', sa.VARCHAR(length=350), nullable=False),
    sa.Column('estoque', sa.INTEGER(), nullable=False),
    sa.Column('preco', sa.FLOAT(), nullable=False),
    sa.Column('formato', sa.VARCHAR(length=40), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=40), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id_estado', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_autor'], ['Autor.id'], name='fk_livro_autor', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_estado'], ['Estado.id'], name='fk_livro_estado', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_genero'], ['GeneroLivro.id'], name='fk_livro_genero', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
